-- Migration 005: Add target companies table and populate initial top tech & finance companies
CREATE TABLE IF NOT EXISTS target_companies (
    name TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_target_companies_enabled ON target_companies(enabled);

INSERT OR IGNORE INTO target_companies (name, enabled) VALUES
    ('Amazon', 1),
    ('Google', 0),
    ('Microsoft', 0),
    ('NVIDIA', 0),
    ('Apple', 0),
    ('Meta', 0),
    ('Netflix', 0),
    ('OpenAI', 0),
    ('Salesforce', 0),
    ('Adobe', 0),
    ('Uber', 0),
    ('Stripe', 0),
    ('Databricks', 0),
    ('Snowflake', 0),
    ('LinkedIn', 0),
    ('GitHub', 0),
    ('Atlassian', 0),
    ('Airbnb', 0),
    ('Coinbase', 0),
    ('Oracle', 0),
    ('Cisco', 0),
    ('Intuit', 0),
    ('ServiceNow', 0),
    ('MongoDB', 0),
    ('Confluent', 0),
    ('Nutanix', 0),
    ('Rubrik', 0),
    ('Cohesity', 0),
    ('Palo Alto Networks', 0),
    ('AMD', 0),
    ('Qualcomm', 0),
    ('MediaTek', 0),
    ('Texas Instruments', 0),
    ('Cadence', 0),
    ('Goldman Sachs', 0),
    ('Morgan Stanley', 0),
    ('JPMorgan Chase', 0),
    ('D.E. Shaw & Co', 0),
    ('Tower Research Capital', 0),
    ('Quadeye', 0),
    ('Arcesium', 0),
    ('BNY Mellon', 0),
    ('Wells Fargo', 0),
    ('Visa', 0),
    ('Mastercard', 0),
    ('PayPal', 0),
    ('Walmart', 0),
    ('Flipkart', 0),
    ('Swiggy', 0),
    ('Zomato', 0),
    ('Zepto', 0),
    ('Meesho', 0),
    ('PhonePe', 0),
    ('Juspay', 0),
    ('Navi', 0),
    ('Sarvam AI', 0),
    ('Glance', 0),
    ('MakeMyTrip', 0);
